puns = [
    "What did the fish say when it hit the wall?\nDam!",
    "What did the grape do when it got stepped on?\nIt let out a little wine.",
    "What did the tree say to autumn?\nLeaf me alone!",
    "I used to be a baker, but I couldn't make enough dough.",
    "I'm a huge fan of whiteboards. They're re-markable!",
    "I used to be a baker, but I kneaded to make a change",
    "Why was the computer cold? It left its Windows open.",
    "What do you call an alligator in a vest? An investigator.",
    "What do you call a snake that works for the government? A civil serpent.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the banana go to the doctor? Because it wasn't peeling well.",
    "Why don't oysters give to charity? Because they're shellfish.",
    "I used to be a barber, but I couldn't cut it.",
    "What do you call a pile of cats? A meowtain.",
    "How do you organize a space party? You planet.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "Why did the jelly donut go to the party? To have a jammin' good time!",
    "Why did the jelly donut go to the museum? To see the jam-packed exhibits!",
    "Why did the jelly donut go to the concert? To see the jam band!",
    "Why did the robot go to the bar? To get a byte!",
    "How does a computer get drunk? It takes screenshots.",
    "I was going to make a belt out of watches, but it was a waist of time.",
    "I used to work at a blanket factory, but it was just a throwaway job.",
    "I wanted to be a chef, but I didn't have the thyme.",
    "When is a door not a door? When it's ajar! ",
    "Why did the cow cross the road? To get to the udder side!",
    "Why did the chicken go to the séance? To get to the other side!",
    "Why was everyone so excited when they saw a talking banana? It was an appeal-ing sight! ",
    "What do you call a bee that can't make up its mind? A maybe! ",
    "How do you keep a lion from charging at you? Take away its credit card! ",
    "After you die, what part of your body is the last to stop working?\nYour pupils, because they dilate... ",
    "You can't plant flowers if you haven't botany",
    "How much does a roof cost?\n Nothing it's on the house",
    "A: What are you?\nB: A harp\nA: You are too small to be a harp\nB: Are you calling me a lyre?",
    "I once knew a spider with a job.  He was a web designer.",
    "Where do bad rainbows go?\n Prism\n It'a a light sentence",
    "Out of all the vegetables, you're a real cut-cumber",
    "I used to be a banker, but I lost interest",
    "Our local bakery burned down\n Now I guess their business is toast",
    "One of my co-workers accidentally stuck his laser pointer in a donut during a presentation.\nNow it's a glazer pointer.",
    "What is a jelly donut's favorite month?\n Jamuary",

    "I don't trust people who do acupuncture, they're back stabbers\n\nI know that this isn't a pun. I'm sorry",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.\n\nI know that this isn't a pun. I'm sorry",
    "I was going to tell you a chemistry joke, but I know I wouldn't get a reaction.\n\nI know that this isn't a pun. I'm sorry",
    "I used to be a baker, but I couldn't rise to the occasion\n\nI know that this isn't a pun. I'm sorry",
    "Why was the math book sad? Because it had too many problems.\n\nI know that this isn't a pun. I'm sorry",
    "Why did the tomato turn red? Because it saw the salad dressing!\n\nI know that this isn't a pun. I'm sorry",
    "I used to play the triangle in a reggae band, but I had to quit because it was always the same old angle.\n\nI know that this isn't a pun. I'm sorry",
    "What do you call a bear with no teeth? A gummy bear.\n\nI know that this isn't a pun. I'm sorry",
    "How do you catch a squirrel? Climb a tree and act like a nut.\n\nI know that this isn't a pun. I'm sorry",
    "Why did the cookie go to the doctor? Because it was feeling crumbly.\n\nI know that this isn't a pun. I'm sorry",
    "Why did the AI cross the road? To get to the other algorithm.\n\nI know that this isn't a pun. I'm sorry",
    "Why did the computer go to the doctor? It had a virus!\n\nI know that this isn't a pun. I'm sorry",
    "I used to play piano by ear, but now I use my hands.\n\nI know that this isn't a pun. I'm sorry",
    "I used to be a tailor, but I wasn't making ends meet.\n\nI know that this isn't a pun. I'm sorry",
    "What did one traffic light say to another? Don't look, I'm changing colors!\n\nI know that this isn't a pun. I'm sorry",
    "I'm reading a book about anti-gravity. It's impossible to put down!\n\nI know that this isn't a pun. I'm sorry",
    "Why was the belt sent to jail? For holding up a pair of pants!\n\nI know that this isn't a pun. I'm sorry",
    "What do you call two chickens sitting on top of each other? A poultry stack!",






]
