from typing import Tuple, List
puzzles: List[Tuple[str, str]] = [
    ("A man is pushing his car along a road when he comes to a hotel. He shouts, 'I'm bankrupt!' Why?",
     "(Answer: The man is playing Monopoly and has landed on a property he can't afford.)"),
    ("A man walks into a store and sees a man he has never seen before. He tells the store owner he will not leave the store until he finds out the stranger's name. How does he find out?",
     "(Answer: The man looks at the stranger's name tag.)"),
    ("Two men are in a boat. One jumps out. Why did the boat not move?",
     "(Answer: The boat was on land.)"),
    ("I am light as a feather, but not even the strongest man can hold me for much longer than a minute. What am I?",
     "Breath"),
    ("I am not alive, but I grow; I don't have lungs, but I need air; I don't have a mouth, but water kills me. What am I?",
     "Fire"),
    ("I can be cracked, made, told, and played. What am I?",
     "A joke"),
    ("I am not alive, but I can die. I don't have muscles, but I move. I don't have a mind, but I can think. What am I?",
     "A Robot"),
    ("'I am always hungry, I must always be fed. The finger I touch, will soon turn red. What am I?'",
     "fire."),
    ("Riddle: I am a word that starts with 'E' and ends with 'E,' but only contains one letter. What am I?",
     "Answer: Envelope"),
    ("Riddle: I am a number that is greater than 99 but less than 1000. I am divisible by 7 and the sum of my digits is 9. What am I?",
     "Answer: 252"),
    ("Riddle: I am a word that starts with 'S' and is often used in a question. What am I?",
     "Answer: Sure"),
    ("Riddle: I am round and full of holes, but I can hold water. What am I?",
     "Answer: A sponge"),
    ("I am something people love or hate, I change people's appearances and thoughts, if you have me, you want to share me, if you share me, you haven't got me. What am I?",
     "(Answer: Secret)"),
    ("What has a head and a tail, but no body?", "A coin)"),
    ("What can you catch but not throw?", " (A cold)"),
    ("What has four eyes but cannot see?", " (Mississippi)"),
    ("I have keys but no locks, I have space but no room, you can enter but can't go outside. What am I?", " (A keyboard)"),
    ("I run but never walk, have a mouth but never talk. I has a head, but never weep and most people have one and use it cheap. What am I?", " (A river) "),
    ("What has a neck but no head?", " (A bottle)"),
    ("What comes down but never goes up?", "  (Rain)"),
    ("What has a ring but no finger?", "  (A telephone)"),
    ("What has hands but can not clap?", "  (A clock)"),
    ("What has a eyes but no face?", "  (A potato)"),
    ("I am full of keys but I cannot open any door. What am I?", "  (A piano)"),
    ("What has a tongue but cannot taste?", " (A shoe)"),
    ("What has a bank but no money?", "  (A river)"),
    ("What can you break, even though you can't touch it?", "  (A promise)"),
    ("What has an eye but cannot see?", "  (A needle)"),
    ("What has a heart but no other organs?", "  (A deck of cards)"),
    ("What can you hear but not touch or see?", "  (Sound)"),
    ("What has a bed but never sleeps? ", " (A river)"),
    ("What has a mouth but cannot eat? ", " (A river)"),
    ("What has a spine but no bones?", "  (A book)"),
    ("What has a foot but no legs? ", " (A snail)"),
    ("What can you fill but never empty?", "  (Your mind)"),
    ("What can you keep after giving it away? ", " (Your word)"),
    ("How many months have 28 days?",
     "Answer: All of them. "),
    ("I have four wings but cannot fly; I never laugh and never cry; On the same spot I’m always found, toiling away with little sound. What am I? ",
     "Answer: A Windmill"),
    ("You can see me in water, but I never get wet. What am I? ",
     "Answer: A reflection. "),
    ("What can you hold in your left hand but not in your right?",
     "Answer: Your own right hand."),
    ("What comes once in a minute, twice in a moment, but never in a thousand years?", " (The letter M)"),
    ("Why did the bicycle fall over?", "  (It was two tired)"),
    ("What is black when you buy it, red when you use it and gray when you throw it away? ", " (Charcoal) "),
    ("Why are ghosts so bad at lying?",
     "  (Because you can see right through them) "),
    ("Where do fish keep their money?", "  (In a river bank) "),
    ("What can fill a room but takes up no space? ", " (Light)"),
    ("What starts with the letter T, ends with the letter T, and has “T” in it?", "  (Teapot) "),
    ("We’re five little items of an everyday sort, you'll find us all in ‘a tennis court’. What are we?",
     "  (Lines: base, service, sideline, net & center) "),
    ("No sooner spoken than broken, what is it?", "  (Silence)"),
    ("You will always see me in the past and I will never be in the present, what am I? ", " (Yesterday)"),
    ("You can drop me from the tallest building and I’ll be fine, but if you drop me in water I die. What am I?", "  (Paper)"),
    ("I am weightless, but you can see me. Put me in a bucket, and I’ll make it lighter? ", " (A hole)"),
    ("What has legs but cannot walk? ", " (A chair) "),
    ("What has many teeth, but never smiles? ", " (A comb)"),
    ("I move very slowly, although I take my time, I am never late. What am I? ",
     " (The second hand of a clock)"),
    ("When it comes, you can’t refuse it, what is it?",
     "  (A greeting or invitation) "),
    ("I can be found everywhere, but almost never seen. What am I? ", " (Air)"),
]

if __name__ == "__main__":
    print(len(puzzles))
